### PR TITLE
Make cluster recovery/restart within k8s possible again

### PR DESCRIPTION
**Pull request by Bananenbieger1234**
Revert some changes of PR#53 concerning cluster recovery and restart scenarios.

Signed-off-by: Dominik Vogt <dominik.vogt@de.markant.com>

**Description of the change**
This PR fixes the following issues:

- https://github.com/bitnami/charts/issues/8721
- https://github.com/bitnami/bitnami-docker-mariadb-galera/issues/75

... and maybe this one as well:

- https://github.com/bitnami/charts/issues/8424

**Benefits**
Cluster recovery/restart works properly.

Steps, which should work after this change:

1. Scale down statefulset (replicas=0)
2. Scale up statefulset again (replicas=3)

Between step 1. and 2. we normally recover an old data snapshot (taken by mariabackup) - but this seems not to be essential for the issue.

**Possible drawbacks**

**Applicable issues**

**Additional information**

I only tested 10.4, but it seems to affect all versions as the code is the same everywhere.

### CODE REVIEW

**Comment by rafariossaa** [comment]
I did the following testing:

-    Install. Three nodes up and running in one galera cluster.
-    Delete nodes one by one. The cluster is aware of the node removal and adds it again once it is restarted.
-    Delete nodes two by two. The cluster is aware of the nodes removal and adds them again once they are restarted.
-    Upscale (helm update ... --set replicaCount=5). The galera cluster adds the new nodes, and the oldest ones are restarted and all are part of a single galera cluster.
-    Downscale (helm update ... --set replicaCount=3). The galera cluster delete the excess nodes and the remaining are restarted. All are part of a single cluster.
-    Upscale sts (kubectl scale statefulset ... --replicas=5)
-    Downscale sts (kubectl scale statefulset ... --replicas=5)
-    Delete + start (reuse PVCs). (helm delete ... / helm install (using same pwds)) (previously, only 1 node, if not you need to force bootstrap)
-    Delete + force start (reusing PVCs). This was tested forcing bootstraping from different nodes
-    Delete + force start (reusing PVCs) + delete pod. This make a already forced node to restart. This lead to new procedured described in chart README as you will need to "remove" the bootstrap forcing env vars from the pod.

**Comment by rafariossaa** [comment]
Now our CI/CD needs to generate and publish a new container image and also update the tags in the chart.

**Comment by rafariossaa** [comment]
The new image was pushed and the chart was updated to reference this new image.

**Comment by jozefrebjak** [comment]
@Bananenbieger1234 @rafariossaa Are you tested this changes with Docker ? Because we had working galera cluster with PR# 53 with MariaDB 10.6.5. Now we are trying to run new Galera cluster with 10.8 TAG and we have the same issues again. We cant restart bootstrap node and have this node back to the galera cluster.

**Comment by rafariossaa** [comment]
@jozefrebjak do you mind opening a new issue and provide info about you scenario there ?
I think that way we can have a better tracking of your issue.

**Pull request merged**
