### PR TITLE
Wait for wsrep

### PR DESCRIPTION
**Pull request by mikk150**
**Description of the change**

Wait until WSREP tells that it is ready to recieve transactions

**Benefits**

on slow storages, if WSREP is not ready, but we can already connect to mariadb initial installation of users fail
because any transaction is rejected by WSREP

**Possible drawbacks**

Sometimes WSREP tells that it is ready, when in fact it is not, but that is problem with storage that is not accessible(Not slow, but plain gone)

**Applicable issues**

**Additional information**

It should probably even replace the need for `DB_INIT_SLEEP_TIME`

### CODE REVIEW

**Comment by migruiz4** [comment]
Hi @mikk150 ,

Thank you very much for you contribution, the additions look good to me.

**Review by migruiz4 — APPROVED** [review]

**Comment by mikk150** [comment]
is it going to be merged?

**Comment by migruiz4** [comment]
Hi @mikk150 ,

I'm sorry for the late response.
The PR hasn't been merged yet because it is going through internal reviewing and testing.

We are working to include your changes in a new release as soon as possible. 

I'm sorry for the inconvenience.

**Comment by mikk150** [comment]
@migruiz4 any news?

**Comment by migruiz4** [comment]
Hi @mikk150,

I'm sorry this task was blocked for so long, we can merge it now.

Sorry for the inconveniences and thank you very much for your contribution.

**Pull request merged**
